version: "3.8"

services:
  db:
    image: postgres:12.2-alpine
    container_name: "database"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - fullstack
    volumes:
      - database_postgres:/var/lib/postgresql/data

  redis-cache:
    image: redis:alpine
    ports:
      - "6379:6379"
    container_name: "cache"
    networks:
      - fullstack

  gogetitdone:
    build: .
    container_name: "gogetitdone"
    environment:
      DB_USER: "psebaraj"
      DB_PASSWORD: "abc123"
      DB_DIALECT: "postgres"
      DB_HOST: "db"
      DB_PORT: "5432"
      REDIS_HOST: "redis-cache"
      REDIS_PORT: "6379"
      REDIS_PASSWORD: ""
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis-cache
    networks:
      - fullstack

volumes:
  database_postgres:

networks:
  fullstack:
    driver: bridge
